schemaBasePath: ./jsonschema/

# Only materialize yaml files.  See TXXXXXX
contentTypes: [yaml]

logLevel: info
shouldGenerateExample: true
skipSchemaTestCases:
  # /mediawiki/recentchange legacy schema has polymorphic
  # nullable types, skip the deterministic types test case.
  '/mediawiki/recentchange/.*':
    - schema-deterministic-types
  # These legacy schemas have object types without a defined schema,
  # so skip the deterministic types test case.
  'change-prop/continue/.*':
    - schema-deterministic-types
  'change-prop/retry/.*':
    - schema-deterministic-types
  'mediawiki/job/.*':
    - schema-deterministic-types
  'mediawiki/page/properties-change/.*':
    - schema-deterministic-types
  # As of jsonschema-tools 1.1.0, removing fields between
  # minor versions fails validation.
  # 'client_ip' was removed between minor versions.
  'fragment/http/1.2.0':
    - schema-version-compatibility
  'mediawiki/client/error/1.1.0':
    - schema-version-compatibility
  '/webrequest/1.0.0':
    - schema-enforced-numeric-bounds
    - schema-deterministic-types
  # mediawiki/page/change (and related) version 1.2.0
  # removes requiredness of the performer field.
  # Skip backwards the compatibility check.
  # https://phabricator.wikimedia.org/T367923
  '/fragment/mediawiki/state/change/page/1.2.0':
    - schema-version-compatibility
  '/mediawiki/page/change/1.2.0':
    - schema-version-compatibility
