schemaBasePath: ./jsonschema/
logLevel: info
skipSchemaTestCases:
  # /mediawiki/recentchange legacy schema has polymorphic
  # nullable types, skip the monomorphic types test case.
  '/mediawiki/recentchange/.*':
    - schema-monomorphic-types
# Temporarily disable numeric bounds enforcement until we are ready to rematerialize
# all schemas with enforced numeric bounds. T258659
enforcedNumericBounds: false