schemaBasePath: ./jsonschema/
logLevel: info
skipSchemaTestCases:
  # /mediawiki/recentchange legacy schema has polymorphic
  # nullable types, skip the monomorphic types test case.
  '/mediawiki/recentchange/.*':
    - schema-monomorphic-types
